### ISSUE TITLE
/v4/projects/<ID>/phases returns 404 for new projects

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#155]
For newly created projects`GET /v4/projects/<ID>/phases` returns error `404 Not Found`.

I've tried with `pshah_manager` and `pshah_cutomer` users.

Here are the new projects I've created:
- https://connect.topcoder-dev.com/projects/6901 (by customer)
- https://connect.topcoder-dev.com/projects/6902 (by manager)

If you open them in console you can see error during `GET /v4/projects/6902/phases`:
```
{
  "id": "605d16e0-a018-48d6-8026-f1b2140243b1",
  "result": {
    "success": false,
    "status": 404,
    "content": {
      "message": "Not Found"
    },
    "debug": "Error: Not Found\n    at respond (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:289:15)\n    at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:248:7)\n    at HttpAmazonESConnector.<anonymous> (/usr/src/app/node_modules/http-aws-es/connector.js:86:11)\n    at IncomingMessage.wrapper (/usr/src/app/node_modules/elasticsearch/node_modules/lodash/index.js:3095:19)\n    at emitNone (events.js:110:20)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1045:12)\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:218:9)"
  }
}
```

**Comment by vikasrohit** [comment]
Closing as it does not seem to appear anymore.
