### ISSUE TITLE
Can't update aliases in productTemplates

### ISSUE THREAD

**Issue by gondzo** [topcoder-platform/tc-project-service#210]
updating product templates without aliases field works properly.

sample call
PATCH https://api.topcoder-dev.com/v4/projects/metadata/productTemplate/51

body
```
param: {id: 51, name: "DUPLICATE-Enterprise Mobile", productKey: "enterprise_mobile", category: "generic",…}
aliases: ["enterprise-mobile"]
0: "enterprise-mobile"
brief: "Enterprise Mobile"
category: "generic"
details: "Enterprise Mobile"
disabled: false
hidden: true
icon: "product-app-app"
id: 51
name: "DUPLICATE-Enterprise Mobile"
productKey: "enterprise_mobile"
subCategory: "generic"
template:<anything>
```

sample response (404)
```
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Error: Not Found<br> &nbsp; &nbsp;at /usr/src/app/dist/routes/index.js:167:13<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:91:12)<br> &nbsp; &nbsp;at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)<br> &nbsp; &nbsp;at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)<br> &nbsp; &nbsp;at compression (/usr/src/app/node_modules/compression/index.js:220:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)<br> &nbsp; &nbsp;at /usr/src/app/node_modules/express/lib/router/index.js:284:7<br> &nbsp; &nbsp;at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)</pre>
</body>
</html>
```

**Comment by vikasrohit** [comment]
https://github.com/topcoder-platform/tc-project-service/pull/209 is already raised to fix this. Will be merging it soon.

**Comment by vikasrohit** [comment]
Closing the issue as it should be fixed now in dev. Thanks @gondzo  for reporting.
