### ISSUE TITLE
SequelizeDatabaseError: column "allowedUsers" does not exist

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#250]
When I try to navigate to any project on DEV the project service returns error 500:

![image](https://user-images.githubusercontent.com/146016/52528546-8417d780-2d1c-11e9-84f1-8c4fcba48030.png)

```
{
  "id": "c0487942-1e07-4cd7-9147-ed08028ccdff",
  "result": {
    "success": false,
    "status": 500,
    "content": {
      "message": "column \"allowedUsers\" does not exist"
    },
    "debug": "SequelizeDatabaseError: column \"allowedUsers\" does not exist\n    at Query.formatError (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:357:14)\n    at Query.<anonymous> (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)\n    at emitOne (events.js:115:13)\n    at Query.emit (events.js:210:7)\n    at Query.handleError (/usr/src/app/node_modules/pg/lib/query.js:108:8)\n    at Connection.<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:171:26)\n    at emitOne (events.js:115:13)\n    at Connection.emit (events.js:210:7)\n    at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:109:12)\n    at emitOne (events.js:115:13)\n    at Socket.emit (events.js:210:7)\n    at addChunk (_stream_readable.js:252:12)\n    at readableAddChunk (_stream_readable.js:239:11)\n    at Socket.Readable.push (_stream_readable.js:197:10)\n    at TCP.onread [as _originalOnread] (net.js:589:20)\n    at TCP.onread (/usr/src/app/node_modules/async-listener/glue.js:188:31)\nFrom previous event:\n    at Query.run (/usr/src/app/node_modules/sequelize/lib/dialects/postgres/query.js:74:17)\n    at /usr/src/app/node_modules/sequelize/lib/sequelize.js:849:20\n    at /usr/src/app/node_modules/retry-as-promised/index.js:39:21\nFrom previous event:\n    at retryAsPromised (/usr/src/app/node_modules/retry-as-promised/index.js:29:10)\n    at /usr/src/app/node_modules/sequelize/lib/sequelize.js:848:12\n    at /usr/src/app/node_modules/continuation-local-storage/context.js:84:17\nFrom previous event:\n    at Promise.then (/usr/src/app/node_modules/sequelize/lib/promise.js:21:17)\n    at module.exports (/usr/src/app/dist/routes/projects/get.js:55:6)\n    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)\n    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)\n    at authorizer.can.then (/usr/src/app/node_modules/tc-core-library-js/lib/middleware/permissions.js:10:9)\n    at propagateAslWrapper (/usr/src/app/node_modules/async-listener/index.js:478:23)\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31\n    at /usr/src/app/node_modules/async-listener/index.js:515:70\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31\n    at <anonymous>"
  }
}
```

fyi @vikasrohit 

To make the Project Service available on DEV, I'll deploy some more earilier commit to DEV https://github.com/topcoder-platform/tc-project-service/tree/feature/dev-previous

**Comment by vikasrohit** [comment]
@maxceem fixed the database and redeployed latest changes back. Seems to work fine for me, let me know if it still there.
