### ISSUE TITLE
Forms, PriceConfig, PlanConfig: creating a new version after deleting fails

### ISSUE THREAD

**Issue by maxceem** [topcoder-platform/tc-project-service#324]
This issue can be reproduced for any model with versions: Forms, PriceConfig, PlanConfig.

How to reproduce:
1. Create two versions of in any model.
2. Delete the second version.
3. Try to create a new version.
4. The server will return an error.

Example:
`POST http://localhost:8001/v4/projects/metadata/planConfig/ptest1/versions`
returns 
```
SequelizeUniqueConstraintError: Validation error
  at Query.formatError (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/dialects/postgres/query.js:326:16)
  at Query.<anonymous> (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/dialects/postgres/query.js:88:19)
  at emitOne (events.js:116:13)
  at Query.emit (events.js:211:7)
  at Query.handleError (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/pg/lib/query.js:108:8)
  at Connection.<anonymous> (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/pg/lib/client.js:171:26)
  at emitOne (events.js:116:13)
  at Connection.emit (events.js:211:7)
  at Socket.<anonymous> (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/pg/lib/connection.js:109:12)
  at emitOne (events.js:116:13)
  at Socket.emit (events.js:211:7)
  at addChunk (_stream_readable.js:263:12)
  at readableAddChunk (_stream_readable.js:250:11)
  at Socket.Readable.push (_stream_readable.js:208:10)
  at TCP.onread [as _originalOnread] (net.js:601:20)
  at TCP.onread (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/async-listener/glue.js:188:31)\nFrom previous event:
  at Query.run (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/dialects/postgres/query.js:74:17)
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/sequelize.js:849:20
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/retry-as-promised/index.js:39:21\nFrom previous event:
  at retryAsPromised (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/retry-as-promised/index.js:29:10)
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/sequelize.js:848:12
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/continuation-local-storage/context.js:84:17\nFrom previous event:
  at Promise.then (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/promise.js:21:17)
  at transactionResolver (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/sequelize.js:1284:40)
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/continuation-local-storage/context.js:84:17\nFrom previous event:
  at Sequelize.transaction (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/sequelize/lib/sequelize.js:1313:12)
  at module.exports (/Users/maks/dev/topcoder/projects/connect/tc-project-service/src/routes/planConfig/version/create.js:35:22)
  at Layer.handle [as handle_request] (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/express/lib/router/layer.js:95:5)
  at next (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/express/lib/router/route.js:137:13)
  at authorizer.can.then (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/tc-core-library-js/lib/middleware/permissions.js:10:9)
  at propagateAslWrapper (/Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/async-listener/index.js:478:23)
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/async-listener/glue.js:188:31
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/async-listener/index.js:515:70
  at /Users/maks/dev/topcoder/projects/connect/tc-project-service/node_modules/async-listener/glue.js:188:31
  at <anonymous>
  at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:229:7)
```

Most likely issues happens because when we determine the number for a new version to use we don't take into account that we use soft-deleting for the forms, se we try to use versions number from the form which has been deleted.

**Comment by vikasrohit** [comment]
CF candidate.
