### ISSUE TITLE
Regression in admin endpoint for migrating metadata to ES

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#485]
Following error is being thrown when trying to sync, using `{{api-url}}/v5/projects/admin/es/migrateFromDb`, the latest metadata in dev env:
```
{
    "message": "[mapper_parsing_exception] failed to parse",
    "debug": "Error: [mapper_parsing_exception] failed to parse\n    at respond (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:349:15)\n    at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:306:7)\n    at done (/usr/src/app/node_modules/http-aws-es/connector.js:48:7)\n    at IncomingMessage.cleanUp (/usr/src/app/node_modules/http-aws-es/src/node.js:20:7)\n    at emitNone (events.js:110:20)\n    at IncomingMessage.emit (events.js:207:7)\n    at endReadableNT (_stream_readable.js:1045:12)\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31\n    at _combinedTickCallback (internal/process/next_tick.js:138:11)\n    at process._tickDomainCallback (internal/process/next_tick.js:218:9)\n    at process.fallback (/usr/src/app/node_modules/async-listener/index.js:565:15)"
}
```

**Comment by vikasrohit** [comment]
@maxceem fyi

**Comment by vikasrohit** [comment]
@maxceem I am not sure what happened, but it worked after some time without any change. I was trying to get local env setup and point it to the dev env and it worked on my local first and then I tried on dev where it worked as well.

**Comment by maxceem** [comment]
Hmm, it's hard to say what could happen without ability to reproduce the situation and check the actual data. I cannot think about any reason for now.
