### ISSUE TITLE
Breaking request

### ISSUE THREAD

**Issue by jmgasper** [topcoder-platform/tc-project-service#572]
This request was found in a recent bug hunt.  This should be handled gracefully by the project-api:

### Request:

GET `https://api.topcoder-dev.com/v5/projects?memberOnly=true&name=%2A%5B%5D%2A&sort=lastActivityAt&status=active`

### Response:

`
Error: [query_parsing_exception] Failed to parse query [*[]*], with { index="projects" & line=1 & col=670 }    at respond (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:349:15)    at checkRespForFailure (/usr/src/app/node_modules/elasticsearch/src/lib/transport.js:306:7)    at done (/usr/src/app/node_modules/http-aws-es/connector.js:48:7)    at IncomingMessage.cleanUp (/usr/src/app/node_modules/http-aws-es/src/node.js:20:7)    at IncomingMessage.emit (events.js:323:22)    at IncomingMessage.EventEmitter.emit (domain.js:482:12)    at endReadableNT (_stream_readable.js:1204:12)    at /usr/src/app/node_modules/async-listener/glue.js:188:31    at processTicksAndRejections (internal/process/task_queues.js:84:21)
`

**Comment by vikasrohit** [comment]
fyi @maxceem

**Comment by maxceem** [comment]
- This request fails when we are trying to search by project name `2A[]*` or `*2A[]*` or `*2A[]`.
- The expected result we should find projects which contain `2A[]`:
  - `2A[]*` - in the beginning of the name
  - `*2A[]` - in the end of the name
  - `*2A[]*` - anywhere in the name
