### ISSUE TITLE
Internal Server Error when reindexing certain projects

### ISSUE THREAD

**Issue by vikasrohit** [topcoder-platform/tc-project-service#654]
"stack": "Error: Request failed with status code 500\n    at createError (/usr/src/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/src/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/src/app/node_modules/axios/lib/adapters/http.js:236:11)\n    at IncomingMessage.emit (events.js:323:22)\n    at IncomingMessage.EventEmitter.emit (domain.js:482:12)\n    at endReadableNT (_stream_readable.js:1204:12)\n    at /usr/src/app/node_modules/async-listener/glue.js:188:31\n    at processTicksAndRejections (internal/process/task_queues.js:84:21)\nFrom previous event:\n    at Immediate.<anonymous> (/usr/src/app/node_modules/async-listener/glue.js:188:31)\n    at processImmediate (internal/timers.js:456:21)\n    at process.topLevelDomainCallback (domain.js:137:15)\nFrom previous event:\n    at prepareProject (/usr/src/app/dist/utils/es.js:172:47)\n    at async indexProjectsRange (/usr/src/app/dist/utils/es.js:227:19)"
    }

**Comment by maxceem** [comment]
I guess something with Member Service requests which we call during project reindexing https://github.com/topcoder-platform/tc-project-service/blob/develop/src/utils/es.js#L168. Beucause I don't see anything else which might return error `Request failed with status code 500`.

**Comment by vikasrohit** [comment]
Make sense. Thanks
